<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>CustomerManagement.Domain</RootNamespace>
	<AssemblyName>CustomerManagement.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\Domain.Entities\CustomerManagement.Domain.Entities.csproj" />
  </ItemGroup>

</Project>
